# Generated by Django 3.2.22 on 2023-11-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='excerpt',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='image_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='book',
            name='synonpis',
            field=models.TextField(default=''),
        ),
    ]
